/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 90c75a15e9cf
 */

import { dlv } from "./dlv.js";

import * as z from "zod";

export interface Env {
  AGENTFABRICAGENTS_COOKIE_AUTH?: string | undefined;
  AGENTFABRICAGENTS_BEARER_AUTH?: string | undefined;

  AGENTFABRICAGENTS_DEBUG?: boolean | undefined;
}

export const envSchema: z.ZodType<Env> = z.object({
  AGENTFABRICAGENTS_COOKIE_AUTH: z.string().optional(),
  AGENTFABRICAGENTS_BEARER_AUTH: z.string().optional(),

  AGENTFABRICAGENTS_DEBUG: z.stringbool().optional(),
});

let envMemo: Env | undefined = undefined;
/**
 * Reads and validates environment variables.
 */
export function env(): Env {
  if (envMemo) {
    return envMemo;
  }

  envMemo = envSchema.parse(
    dlv(globalThis, "process.env") ?? dlv(globalThis, "Deno.env") ?? {},
  );
  return envMemo;
}

/**
 * Clears the cached env object. Useful for testing with a fresh environment.
 */
export function resetEnv() {
  envMemo = undefined;
}
